---
- hosts: all
  tasks:
    - yum:
        name: httpd
        state: latest
      notify: print msg package updated
    - copy:
        src: ./index.html
        dest: /var/www/html
      notify: restart apache service
    - service:
        name: httpd
        state: started
    # handler will not run because a.txt does not exist
    - lineinfile:
        path: ./a.txt
        line: Hello Pakistan
  handlers:
    - name: restart apache service
      service:
        name: httpd
        state: restarted 
    - name: print msg package updated
      debug:
        msg: package httpd is updated

