---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Installing Web Package
      block:
        - name: Installing Httpd
          yum:
            name: httpd
            #name: httpd-dafa   for rescue
            state: latest
      rescue:
        - name: Installing nginx
          yum:
            name: nginx
            state: latest
      always:
        - debug:
            msg: web package is installed
           
