---
- hosts: all
  gather_facts: yes
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: add a line in the index.html which should reflect the IP of the server where it is copied
      lineinfile:
        path: /var/www/html/index.html
        line: Hello, This is a reply from the server IP {{ ansible_default_ipv4.address}}
    - name: start the service
      service:
        name: httpd
        state: started
