---
- hosts: all
  gather_facts: yes
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: copy a file  
      template:
        src: ./index.html
        dest: /var/www/html/index.html
    - name: start the service
      service:
        name: httpd
        state: started
