---
- hosts: all
  vars:
    users:
      - Tanveer
      - Naveed
      - Waqas
      - Aleem
  gather_facts: yes
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: copy a file  
      template:
        src: ./index2.html.j2
        dest: /var/www/html/index.html
    - name: start the service
      service:
        name: httpd
        state: started
