---
- name: Playbook for Loop
  hosts: all
  tasks:
    - name: "create some test users"
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
        groups: "root"
      with_sequence: start=0 end=32 format=testuser%02x
