---
- name: Playbook for Loop
  hosts: all
  tasks:
    - name: create a series of directories with even numbers for some reason
      ansible.builtin.file:
        dest: "/tan{{ item }}"
        state: directory
      with_sequence: start=4 end=16 stride=2
