---
- name: Playbook Variables --> Call Variables from vars file
  hosts: all
  vars_files: 
    - ./vars.yml
  tasks: 
    - name: This module will print a msg
      debug:
        msg: "{{message}}"
