---
- name: Playbook for File Modules
  hosts: all
  tasks:
    - name: Copy a file to managed hosts
      ansible.builtin.copy:
        src: file.txt
        dest: /file123.txt
  # - name: Retrieve SSH key from reference host
  #    ansible.builtin.fetch:
  #      src: /home/{{ user }}/.ssh/id_rsa.pub
  #      dest: files/keys/{{ user }}.pub
