---
- hosts: all
  gather_facts: true
  tasks:
    - name: Set custom_host
      ansible.builtin.set_fact:
        custom_host: "{{ ansible_facts['ansible_local']['custom'] }}"
    - name: Print Custom Facts
      debug:
        msg:
          - "{{ custom_host.users.user1 }}"
        # - "{{ custom_host }}"
