---
- name: Playbook Selecting Managed Host with Host Patterns 
  hosts: server
  #hosts: 192.168.2.1
  #hosts: lab
  #hosts: all
  #hosts: ungrouped
  #hosts: '*'
  #hosts: '*.example.com'
  #hosts: '192.168.2.*'
  #hosts: 'datacenter*'
  #hosts: 'data*'
  #hosts: labhost1.example.com,test2.example.com,192.168.2.2
  #hosts: lab,datacenter1
  #hosts: lab,data*,192.168.2.2
  
  #For example, based on our example inventory, the following host pattern matches machines in thelab group only if they are also in the datacenter1 group:
  #hosts: lab,&datacenter1
  
  #This example matches all hosts defined in the datacenter group, except test2.example.com based on the example inventory:
  #hosts: datacenter,!test2.example.com
  
  #hosts: all,!datacenter1
  
  tasks:
    - name: Ping the host
      ping:
  
