---
- hosts: all
  tasks:
    - name: Install the httpd package
      yum:
        name: httpd
        state: present
    - name: copy the file
      file:
        path: /abc
        state: directory
    - name: Import task file and set variables
      import_tasks: task3.yaml
      vars:
        msg_task3: Hello this is from task3.yaml 


