---
- name: Restart HTTPD if Postfix is Running
  hosts: all
  gather_facts: yes
  tasks:
    - name: Get Postfix server status
      #ansible.builtin.command: /usr/bin/systemctl is-active postfix
      ansible.builtin.command: /usr/bin/systemctl is-active httpd
      register: result
    - name: Restart Apache HTTPD based on Postfix status
      ansible.builtin.service:
        name: httpd
        state: restarted
      when: result.rc == 0
